import random
name_data = [
      {"name": "Rauf", "gender": "male"},
    {"name": "Ali", "gender": "male"},
    {"name": "Narmin", "gender": "female"},
    {"name": "Elnur", "gender": "male"},
    {"name": "Aygun", "gender": "female"},
    # Add more entries...
    # Entries 6 to 500
    # ...
    {"name": "Gulnar", "gender": "female"},
    {"name": "Ramin", "gender": "male"},
    {"name": "Sara", "gender": "female"},
    {"name": "Orxan", "gender": "male"},
    {"name": "Sevinc", "gender": "female"},
    # Add more entries...
    # Entries 501 to 1000
    # ...
    {"name": "Huseyn", "gender": "male"},
    {"name": "Gunay", "gender": "female"},
    {"name": "Tural", "gender": "male"},
    {"name": "Fidan", "gender": "female"},
    {"name": "Farid", "gender": "male"},
    # Add more entries...
    # Entries 1001 to 1500
    # ...
    {"name": "Nijat", "gender": "male"},
    {"name": "Nazrin", "gender": "female"},
    {"name": "Kamran", "gender": "male"},
    {"name": "Aysu", "gender": "female"},
    {"name": "Togrul", "gender": "male"},
    # Add more entries...
    # Entries 1501 to 2000
    # ...
    {"name": "Elvin", "gender": "male"},
    {"name": "Roya", "gender": "female"},
    {"name": "Emin", "gender": "male"},
    {"name": "Ayten", "gender": "female"},
    {"name": "Rustam", "gender": "male"},
    # Add more entries...
    # Entries 2001 to 2500
    # ...
    {"name": "Gulshan", "gender": "female"},
    {"name": "Vusal", "gender": "male"},
    {"name": "Firuza", "gender": "female"},
    {"name": "Rovshan", "gender": "male"},
    {"name": "Lala", "gender": "female"},
    # Add more entries...
    # Entries 2501 to 3000
    # ...
    {"name": "Arif", "gender": "male"},
    {"name": "Tahira", "gender": "female"},
    {"name": "Rustam", "gender": "male"},
    {"name": "Nigar", "gender": "female"},
    {"name": "Ayaz", "gender": "male"},
    # Add more entries...
    # Entries 3001 to 3500
    # ...
    {"name": "Samir", "gender": "male"},
    {"name": "Ziba", "gender": "female"},
    {"name": "Nadir", "gender": "male"},
    {"name": "Sevda", "gender": "female"},
    {"name": "Azer", "gender": "male"},
    {"name": "Turkan", "gender": "female"},
    {"name": "Murad", "gender": "male"},
    {"name": "Firuze", "gender": "female"},
    {"name": "Ramil", "gender": "male"},
    {"name": "Gulnaz", "gender": "female"},
    # Add more entries...
    # Entries 4501 to 5000
    {"name": "Rashad", "gender": "male"},
    {"name": "Leyla", "gender": "female"},
    {"name": "Kamal", "gender": "male"},
    {"name": "Nergiz", "gender": "female"},
    {"name": "Elshad", "gender": "male"},
    {"name": "Ali", "gender": "male"},
    {"name": "Ayten", "gender": "female"},
    {"name": "Narmin", "gender": "female"},
    {"name": "Murad", "gender": "male"},
    {"name": "Elnur", "gender": "male"},
    {"name": "Gulnar", "gender": "female"},
    {"name": "Rauf", "gender": "male"},
    {"name": "Leyla", "gender": "female"},
    {"name": "Nizami", "gender": "male"},
    {"name": "Sevda", "gender": "female"},
    {"name": "Orxan", "gender": "male"},
    {"name": "Aygun", "gender": "female"},
    {"name": "Samir", "gender": "male"},
    {"name": "Elmira", "gender": "female"},
    {"name": "Elmir", "gender": "male"},
    {"name": "Nazrin", "gender": "female"},
    {"name": "Vugar", "gender": "male"},
    {"name": "Sabina", "gender": "female"},
    {"name": "Emin", "gender": "male"},
    {"name": "Gunel", "gender": "female"},
    {"name": "Rashad", "gender": "male"},
    {"name": "Aysel", "gender": "female"},
    {"name": "Sahib", "gender": "male"},
    {"name": "Gulshan", "gender": "female"},
    {"name": "Tural", "gender": "male"},
    {"name": "Fidan", "gender": "female"},
    {"name": "Rasim", "gender": "male"},
    {"name": "Zuleykha", "gender": "female"},
    {"name": "Vasif", "gender": "male"},
    {"name": "Aylin", "gender": "female"},
    {"name": "Ramin", "gender": "male"},
    {"name": "Zarina", "gender": "female"},
    {"name": "Vugar", "gender": "male"},
    {"name": "Aysel", "gender": "female"},
    {"name": "Sahib", "gender": "male"},
    {"name": "Gulshan", "gender": "female"},
    {"name": "Tural", "gender": "male"},
    {"name": "Fidan", "gender": "female"},
    {"name": "Rasim", "gender": "male"},
    {"name": "Zuleykha", "gender": "female"},
    {"name": "Vasif", "gender": "male"},
    {"name": "Aylin", "gender": "female"},
    {"name": "Ramin", "gender": "male"},
    {"name": "Zarina", "gender": "female"},
    {"name": "Vugar", "gender": "male"},
    {"name": "Aysel", "gender": "female"},
    {"name": "Sahib", "gender": "male"},
    {"name": "Gulshan", "gender": "female"},
    {"name": "Tural", "gender": "male"},
    {"name": "Fidan", "gender": "female"},
    {"name": "Rasim", "gender": "male"},
    {"name": "Zuleykha", "gender": "female"},
    {"name": "Vasif", "gender": "male"},
    {"name": "Aylin", "gender": "female"},
    {"name": "Ramin", "gender": "male"},
    {"name": "Zarina", "gender": "female"},
    {"name": "Fikrat", "gender": "male"},
    {"name": "Lala", "gender": "female"},
    {"name": "Javid", "gender": "male"},
    {"name": "Roya", "gender": "female"},
    {"name": "Farid", "gender": "male"},
    {"name": "Parvana", "gender": "female"},
    {"name": "Namik", "gender": "male"},
    {"name": "Gulnara", "gender": "female"},
    {"name": "Nadir", "gender": "male"},
    {"name": "Leyla", "gender": "female"},
    {"name": "Samir", "gender": "male"},
    {"name": "Nigar", "gender": "female"},
    {"name": "Elgun", "gender": "male"},
    {"name": "Gulshan", "gender": "female"},
    {"name": "Rufat", "gender": "male"},
    {"name": "Fidan", "gender": "female"},
    {"name": "Rustam", "gender": "male"},
    {"name": "Leyla", "gender": "female"},
    {"name": "Elchin", "gender": "male"},
    {"name": "Sabina", "gender": "female"},
    {"name": "Nijat", "gender": "male"},
    {"name": "Zarina", "gender": "female"},
    {"name": "Vusal", "gender": "male"},
    {"name": "Aylin", "gender": "female"},
    {"name": "Ramin", "gender": "male"},
    {"name": "Ayla", "gender": "female"},
    {"name": "Emin", "gender": "male"},
    {"name": "Nergiz", "gender": "female"},
    {"name": "Togrul", "gender": "male"},
    {"name": "Fidan", "gender": "female"},
    {"name": "Rafig", "gender": "male"},
    {"name": "Aygun", "gender": "female"},
    {"name": "Ruslan", "gender": "male"},
    {"name": "Lala", "gender": "female"},
    {"name": "Eldar", "gender": "male"},
    {"name": "Nazrin", "gender": "female"},
    {"name": "Vugar", "gender": "male"},
    {"name": "Aylin", "gender": "female"},
    {"name": "Ramin", "gender": "male"},
    {"name": "Zarina", "gender": "female"},
    {"name": "Vugar", "gender": "male"},
    {"name": "Aysel", "gender": "female"},
    {"name": "Sahib", "gender": "male"},
    {"name": "Gulshan", "gender": "female"},
    {"name": "Tural", "gender": "male"},
    {"name": "Fidan", "gender": "female"},
    {"name": "Rasim", "gender": "male"},
    {"name": "Zuleykha", "gender": "female"},
    {"name": "Vasif", "gender": "male"},
    {"name": "Aylin", "gender": "female"},
    {"name": "Ramin", "gender": "male"},
    {"name": "Zarina", "gender": "female"},
    {"name": "Fikrat", "gender": "male"},
    {"name": "Lala", "gender": "female"},
    {"name": "Javid", "gender": "male"},
    {"name": "Roya", "gender": "female"},
    {"name": "Farid", "gender": "male"},
    {"name": "Parvana", "gender": "female"},
    {"name": "Namik", "gender": "male"},
    {"name": "Gulnara", "gender": "female"},
    {"name": "Nadir", "gender": "male"},
    {"name": "Leyla", "gender": "female"},
    {"name": "Samir", "gender": "male"},
    {"name": "Nigar", "gender": "female"},
    {"name": "Elgun", "gender": "male"},
    {"name": "Gulshan", "gender": "female"},
    {"name": "Rufat", "gender": "male"},
    {"name": "Fidan", "gender": "female"},
    {"name": "Rustam", "gender": "male"},
    {"name": "Leyla", "gender": "female"},
    {"name": "Elchin", "gender": "male"},
    {"name": "Sabina", "gender": "female"},
    {"name": "Nijat", "gender": "male"},
    {"name": "Zarina", "gender": "female"},
    {"name": "Vusal", "gender": "male"},
    {"name": "Aylin", "gender": "female"},
    {"name": "Ramin", "gender": "male"},
    {"name": "Ayla", "gender": "female"},
    {"name": "Emin", "gender": "male"},
    {"name": "Nergiz", "gender": "female"},
    {"name": "Togrul", "gender": "male"},
    {"name": "Fidan", "gender": "female"},
    {"name": "Rafig", "gender": "male"},
    {"name": "Aygun", "gender": "female"},
    {"name": "Ruslan", "gender": "male"},
    {"name": "Lala", "gender": "female"},
    {"name": "Eldar", "gender": "male"},
    {"name": "Nazrin", "gender": "female"},
    {"name": "Vugar", "gender": "male"},
    {"name": "Aylin", "gender": "female"},
    {"name": "Ramin", "gender": "male"},
    {"name": "Zarina", "gender": "female"},
    {"name": "Vugar", "gender": "male"},
    {"name": "Aysel", "gender": "female"},
]
surname_data = {
    "male": [
        "Aliyev",
        "Ismayilov",
        "Mammadov",
        "Huseynov",
        "Jafarov",
        "Abdullayev",
        "Rzayev",
        "Nasirov",
        "Safarov",
        "Hasanov",
        "Hajiyev",
        "Ahmadov",
        "Mustafayev",
        "Ibrahimov",
        "Mammadaliyev",
        "Quliyev",
        "Mirzayev",
        "Guliyev",
        "Sadigov",
        "Orujov",
        "Qurbanov",
        "Jabbarov",
        "Nabiyev",
        "Qadirov",
        "Rahimov",
        "Mahmudov",
        "Farajov",
        "Rustamov",
        "Akhundov"
    ],
    "female": [
        "Aliyeva",
        "Ismayilova",
        "Mammadova",
        "Huseynova",
        "Jafarova",
        "Abdullayeva",
        "Rzayeva",
        "Nasirova",
        "Safarova",
        "Hasanova",
        "Hajiyeva",
        "Ahmadova",
        "Mustafayeva",
        "Ibrahimova",
        "Mammadaliyeva",
        "Quliyeva",
        "Mirzayeva",
        "Guliyeva",
        "Sadigova",
        "Orujova",
        "Qurbanova",
        "Jabbarova",
        "Nabiyeva",
        "Qadirova",
        "Rahimova",
        "Mahmudova",
        "Farajova",
        "Rustamova",
        "Akhundova"
    ]
}

def generate_random_person():
    gender = random.choice(["male", "female"])
    name = random.choice([data["name"] for data in name_data if data["gender"] == gender])
    surname = random.choice(surname_data[gender])
    return f"{name} {surname}"

def generate_fake_email(person_name):
    name = person_name.replace(" ", "").lower()
    random_number = random.randint(1, 999)
    email = f"{name}{random_number}@mail.com"
    return email
i=0
def generaterandom(n):
    i = 0
    results = []
    while i < n:
        i += 1
        person_name = generate_random_person()
        fake_email = generate_fake_email(person_name)
        results.append((person_name, fake_email))
    return results

        
        
       